-- ---------------------------------------------------------------------------
-- 212 — Scheduled blog publishing via QStash
--
-- Adds the small bits of schema we need to durable-schedule a blog post
-- to flip from 'scheduled' → 'published' at a future timestamp using
-- Upstash QStash (instead of Vercel cron):
--
--   1. Extends `blog_posts.status` to allow the value 'scheduled'.
--   2. Adds `qstash_message_id` so we can CANCEL or REPLACE an existing
--      QStash schedule when the author re-edits or deletes a draft —
--      otherwise we'd publish a deleted post hours later.
--
-- Idempotent — safe to re-run on environments where the constraint or
-- column already exist.
-- ---------------------------------------------------------------------------

-- Drop the old narrow check constraint (its name is auto-generated by
-- Postgres as "<table>_<column>_check") and replace it with one that
-- also accepts 'scheduled'. We DO NOT touch existing rows.
ALTER TABLE blog_posts
  DROP CONSTRAINT IF EXISTS blog_posts_status_check;

ALTER TABLE blog_posts
  ADD CONSTRAINT blog_posts_status_check
  CHECK (status IN ('draft','scheduled','published','archived'));

-- Track the QStash message id we enqueued for this post so we can cancel
-- it if the author edits or deletes the draft before the schedule fires.
ALTER TABLE blog_posts
  ADD COLUMN IF NOT EXISTS qstash_message_id VARCHAR(255);

-- Useful for the auto-publish endpoint to look up by id quickly.
CREATE INDEX IF NOT EXISTS idx_blog_posts_qstash_msg
  ON blog_posts(qstash_message_id)
  WHERE qstash_message_id IS NOT NULL;
